# Generated by Django 5.1.6 on 2025-03-05 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bookedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
