# Generated by Django 5.1.6 on 2025-03-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_movie_youtube_trailer_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
