# Generated by Django 5.1.6 on 2025-03-02 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_workoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
