# Generated by Django 5.1.6 on 2025-03-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_movie_remove_profile_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_poster/'),
        ),
    ]
