# Generated by Django 5.1.6 on 2025-03-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_booking_seats_booked_remove_booking_showtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingrow',
            name='showtime',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='SeatingRow',
        ),
    ]
