# Generated by Django 5.1.6 on 2025-03-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_bookedticket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedTicket',
        ),
    ]
