# Generated by Django 5.1.6 on 2025-03-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_booking_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_numbers',
            field=models.TextField(default=1),
        ),
    ]
