# Generated by Django 5.1.6 on 2025-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_booking_seats_booking_seats_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_numbers',
            field=models.TextField(default=''),
        ),
    ]
