# Generated by Django 5.1.6 on 2025-03-04 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('is_taken', models.BooleanField(default=False)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.showtime')),
            ],
        ),
    ]
