# Generated by Django 5.1.6 on 2025-03-04 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theater',
        ),
        migrations.AddField(
            model_name='showtime',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='users.movie'),
        ),
    ]
