# Generated by Django 5.1.6 on 2025-03-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_showtime_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='showtime',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='SeatingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_rows', to='users.showtime')),
            ],
        ),
    ]
